server:
  port : 8083

spring:
  application:
    name: program-service
  flyway:
    enabled: false

  # url for spring boot admin client service
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost
        url: http://localhost:8082


  # Datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/program_db
    username: postgres
    password: password

app:
  egoPublicKeyUrl: "https://ego.qa.cancercollaboratory.org/api/oauth/token/public_key"
  grpcPort: 50051

# set this flag in Spring 2.0 because of this open issue: https://hibernate.atlassian.net/browse/HHH-12368
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true

logging:
  level:
    root: ERROR
    #org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    #org.springframework.boot: INFO
    org.icgc.argo.program_service: DEBUG

management.endpoints.web.exposure.include: "*"

# Hibernate SQL Debugging
#spring.jpa.properties.hibernate.format_sql: true
#logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.hibernate.type.descriptor.sql: TRACE


# When you are desperate, use this...
#logging.level.org.hibernate: TRACE

---
###############################################################################
# Profile - "test"
###############################################################################
spring:
  profiles: test

spring.datasource:
  driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  url: jdbc:tc:postgresql:9.5.13://localhost:5432/program_db?TC_INITFUNCTION=org.icgc.argo.program_service.test.FlywayInit::initTestContainers

  username: postgres
  password:

app:
  grpcPort: 50052

---
###############################################################################
# Profile - "auth"
###############################################################################

spring:
  profiles: auth
