spring.main.banner-mode: 'off'


---
###############################################################################
# Profile - "auth"
###############################################################################
ego:
  publicKeyUrl: "https://ego.qa.cancercollaboratory.org/api/oauth/token/public_key"

spring:
  profiles: auth