--Populate data for Institution, Country, and Region --
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

INSERT INTO institution (id, name)
VALUES
  (uuid_generate_v4(), 'OICR'),
  (uuid_generate_v4(), 'FBI');

INSERT INTO country (id, name)
VALUES
  (uuid_generate_v4(),  'Afghanistan' ),
  (uuid_generate_v4(),  'Aland Islands' ),
  (uuid_generate_v4(),  'Albania' ),
  (uuid_generate_v4(),  'Algeria' ),
  (uuid_generate_v4(),  'American Samoa' ),
  (uuid_generate_v4(),  'Andorra' ),
  (uuid_generate_v4(),  'Angola' ),
  (uuid_generate_v4(),  'Anguilla' ),
  (uuid_generate_v4(),  'Antarctica' ),
  (uuid_generate_v4(),  'Antigua and Barbuda' ),
  (uuid_generate_v4(),  'Argentina' ),
  (uuid_generate_v4(),  'Armenia' ),
  (uuid_generate_v4(),  'Aruba' ),
  (uuid_generate_v4(),  'Australia' ),
  (uuid_generate_v4(),  'Austria' ),
  (uuid_generate_v4(),  'Azerbaijan' ),
  (uuid_generate_v4(),  'Bahamas' ),
  (uuid_generate_v4(),  'Bahrain' ),
  (uuid_generate_v4(),  'Bangladesh' ),
  (uuid_generate_v4(),  'Barbados' ),
  (uuid_generate_v4(),  'Belarus' ),
  (uuid_generate_v4(),  'Belgium' ),
  (uuid_generate_v4(),  'Belize' ),
  (uuid_generate_v4(),  'Benin' ),
  (uuid_generate_v4(),  'Bermuda' ),
  (uuid_generate_v4(),  'Bhutan' ),
  (uuid_generate_v4(),  'Bolivia' ),
  (uuid_generate_v4(),  'Bosnia and Herzegovina' ),
  (uuid_generate_v4(),  'Botswana' ),
  (uuid_generate_v4(),  'Bouvet Island' ),
  (uuid_generate_v4(),  'Brazil' ),
  (uuid_generate_v4(),  'British Indian Ocean Territory' ),
  (uuid_generate_v4(),  'Brunei' ),
  (uuid_generate_v4(),  'Bulgaria' ),
  (uuid_generate_v4(),  'Burkina Faso' ),
  (uuid_generate_v4(),  'Burundi' ),
  (uuid_generate_v4(),  'Cambodia' ),
  (uuid_generate_v4(),  'Cameroon' ),
  (uuid_generate_v4(),  'Canada' ),
  (uuid_generate_v4(),  'Cape Verde' ),
  (uuid_generate_v4(),  'Cayman Islands' ),
  (uuid_generate_v4(),  'Central African Republic' ),
  (uuid_generate_v4(),  'Chad' ),
  (uuid_generate_v4(),  'Chile' ),
  (uuid_generate_v4(),  'China' ),
  (uuid_generate_v4(),  'Christmas Island' ),
  (uuid_generate_v4(),  'Cocos (Keeling) Islands' ),
  (uuid_generate_v4(),  'Colombia' ),
  (uuid_generate_v4(),  'Comoros' ),
  (uuid_generate_v4(),  'Congo' ),
  (uuid_generate_v4(),  'Democratic Republic of the Congo' ),
  (uuid_generate_v4(),  'Cook Islands' ),
  (uuid_generate_v4(),  'Costa Rica' ),
  (uuid_generate_v4(),  'Cote D''Ivoire' ),
  (uuid_generate_v4(),  'Croatia' ),
  (uuid_generate_v4(),  'Cuba' ),
  (uuid_generate_v4(),  'Cyprus' ),
  (uuid_generate_v4(),  'Czech Republic' ),
  (uuid_generate_v4(),  'Denmark' ),
  (uuid_generate_v4(),  'Djibouti' ),
  (uuid_generate_v4(),  'Dominica' ),
  (uuid_generate_v4(),  'Dominican Republic' ),
  (uuid_generate_v4(),  'Ecuador' ),
  (uuid_generate_v4(),  'Egypt' ),
  (uuid_generate_v4(),  'El Salvador' ),
  (uuid_generate_v4(),  'Equatorial Guinea' ),
  (uuid_generate_v4(),  'Eritrea' ),
  (uuid_generate_v4(),  'Estonia' ),
  (uuid_generate_v4(),  'Ethiopia' ),
  (uuid_generate_v4(),  'Falkland Islands)' ),
  (uuid_generate_v4(),  'Faroe Islands' ),
  (uuid_generate_v4(),  'Fiji' ),
  (uuid_generate_v4(),  'Finland' ),
  (uuid_generate_v4(),  'France' ),
  (uuid_generate_v4(),  'French Guiana' ),
  (uuid_generate_v4(),  'French Polynesia' ),
  (uuid_generate_v4(),  'French Southern Territories' ),
  (uuid_generate_v4(),  'Gabon' ),
  (uuid_generate_v4(),  'Gambia' ),
  (uuid_generate_v4(),  'Georgia' ),
  (uuid_generate_v4(),  'Germany' ),
  (uuid_generate_v4(),  'Ghana' ),
  (uuid_generate_v4(),  'Gibraltar' ),
  (uuid_generate_v4(),  'Greece' ),
  (uuid_generate_v4(),  'Greenland' ),
  (uuid_generate_v4(),  'Grenada' ),
  (uuid_generate_v4(),  'Guadeloupe' ),
  (uuid_generate_v4(),  'Guam' ),
  (uuid_generate_v4(),  'Guatemala' ),
  (uuid_generate_v4(),  'Guernsey' ),
  (uuid_generate_v4(),  'Guinea' ),
  (uuid_generate_v4(),  'Guinea-Bissau' ),
  (uuid_generate_v4(),  'Guyana' ),
  (uuid_generate_v4(),  'Haiti' ),
  (uuid_generate_v4(),  'Heard Island & Mcdonald Islands' ),
  (uuid_generate_v4(),  'Vatican City' ),
  (uuid_generate_v4(),  'Honduras' ),
  (uuid_generate_v4(),  'Hong Kong' ),
  (uuid_generate_v4(),  'Hungary' ),
  (uuid_generate_v4(),  'Iceland' ),
  (uuid_generate_v4(),  'India' ),
  (uuid_generate_v4(),  'Indonesia' ),
  (uuid_generate_v4(),  'Iran' ),
  (uuid_generate_v4(),  'Iraq' ),
  (uuid_generate_v4(),  'Ireland' ),
  (uuid_generate_v4(),  'Isle Of Man' ),
  (uuid_generate_v4(),  'Israel' ),
  (uuid_generate_v4(),  'Italy' ),
  (uuid_generate_v4(),  'Jamaica' ),
  (uuid_generate_v4(),  'Japan' ),
  (uuid_generate_v4(),  'Jersey' ),
  (uuid_generate_v4(),  'Jordan' ),
  (uuid_generate_v4(),  'Kazakhstan' ),
  (uuid_generate_v4(),  'Kenya' ),
  (uuid_generate_v4(),  'Kiribati' ),
  (uuid_generate_v4(),  'Korea' ),
  (uuid_generate_v4(),  'Kuwait' ),
  (uuid_generate_v4(),  'Kyrgyzstan' ),
  (uuid_generate_v4(),  'Laos' ),
  (uuid_generate_v4(),  'Latvia' ),
  (uuid_generate_v4(),  'Lebanon' ),
  (uuid_generate_v4(),  'Lesotho' ),
  (uuid_generate_v4(),  'Liberia' ),
  (uuid_generate_v4(),  'Libya' ),
  (uuid_generate_v4(),  'Liechtenstein' ),
  (uuid_generate_v4(),  'Lithuania' ),
  (uuid_generate_v4(),  'Luxembourg' ),
  (uuid_generate_v4(),  'Macao' ),
  (uuid_generate_v4(),  'Macedonia' ),
  (uuid_generate_v4(),  'Madagascar' ),
  (uuid_generate_v4(),  'Malawi' ),
  (uuid_generate_v4(),  'Malaysia' ),
  (uuid_generate_v4(),  'Maldives' ),
  (uuid_generate_v4(),  'Mali' ),
  (uuid_generate_v4(),  'Malta' ),
  (uuid_generate_v4(),  'Marshall Islands' ),
  (uuid_generate_v4(),  'Martinique' ),
  (uuid_generate_v4(),  'Mauritania' ),
  (uuid_generate_v4(),  'Mauritius' ),
  (uuid_generate_v4(),  'Mayotte' ),
  (uuid_generate_v4(),  'Mexico' ),
  (uuid_generate_v4(),  'Federated States of Micronesia' ),
  (uuid_generate_v4(),  'Moldova' ),
  (uuid_generate_v4(),  'Monaco' ),
  (uuid_generate_v4(),  'Mongolia' ),
  (uuid_generate_v4(),  'Montenegro' ),
  (uuid_generate_v4(),  'Montserrat' ),
  (uuid_generate_v4(),  'Morocco' ),
  (uuid_generate_v4(),  'Mozambique' ),
  (uuid_generate_v4(),  'Myanmar' ),
  (uuid_generate_v4(),  'Namibia' ),
  (uuid_generate_v4(),  'Nauru' ),
  (uuid_generate_v4(),  'Nepal' ),
  (uuid_generate_v4(),  'Netherlands' ),
  (uuid_generate_v4(),  'Netherlands Antilles' ),
  (uuid_generate_v4(),  'New Caledonia' ),
  (uuid_generate_v4(),  'New Zealand' ),
  (uuid_generate_v4(),  'Nicaragua' ),
  (uuid_generate_v4(),  'Niger' ),
  (uuid_generate_v4(),  'Nigeria' ),
  (uuid_generate_v4(),  'Niue' ),
  (uuid_generate_v4(),  'Norfolk Island' ),
  (uuid_generate_v4(),  'Northern Mariana Islands' ),
  (uuid_generate_v4(),  'Norway' ),
  (uuid_generate_v4(),  'Oman' ),
  (uuid_generate_v4(),  'Pakistan' ),
  (uuid_generate_v4(),  'Palau' ),
  (uuid_generate_v4(),  'Palestine' ),
  (uuid_generate_v4(),  'Panama' ),
  (uuid_generate_v4(),  'Papua New Guinea' ),
  (uuid_generate_v4(),  'Paraguay' ),
  (uuid_generate_v4(),  'Peru' ),
  (uuid_generate_v4(),  'Philippines' ),
  (uuid_generate_v4(),  'Pitcairn' ),
  (uuid_generate_v4(),  'Poland' ),
  (uuid_generate_v4(),  'Portugal' ),
  (uuid_generate_v4(),  'Puerto Rico' ),
  (uuid_generate_v4(),  'Qatar' ),
  (uuid_generate_v4(),  'Reunion' ),
  (uuid_generate_v4(),  'Romania' ),
  (uuid_generate_v4(),  'Russia' ),
  (uuid_generate_v4(),  'Rwanda' ),
  (uuid_generate_v4(),  'Saint Barthelemy' ),
  (uuid_generate_v4(),  'Saint Helena' ),
  (uuid_generate_v4(),  'Saint Kitts and Nevis' ),
  (uuid_generate_v4(),  'Saint Lucia' ),
  (uuid_generate_v4(),  'Saint Martin' ),
  (uuid_generate_v4(),  'Saint Pierre and Miquelon' ),
  (uuid_generate_v4(),  'Saint Vincent and Grenadines' ),
  (uuid_generate_v4(),  'Samoa' ),
  (uuid_generate_v4(),  'San Marino' ),
  (uuid_generate_v4(),  'Sao Tome and Principe' ),
  (uuid_generate_v4(),  'Saudi Arabia' ),
  (uuid_generate_v4(),  'Senegal' ),
  (uuid_generate_v4(),  'Serbia' ),
  (uuid_generate_v4(),  'Seychelles' ),
  (uuid_generate_v4(),  'Sierra Leone' ),
  (uuid_generate_v4(),  'Singapore' ),
  (uuid_generate_v4(),  'Slovakia' ),
  (uuid_generate_v4(),  'Slovenia' ),
  (uuid_generate_v4(),  'Solomon Islands' ),
  (uuid_generate_v4(),  'Somalia' ),
  (uuid_generate_v4(),  'South Africa' ),
  (uuid_generate_v4(),  'South Georgia and Sandwich Islands' ),
  (uuid_generate_v4(),  'Spain' ),
  (uuid_generate_v4(),  'Sri Lanka' ),
  (uuid_generate_v4(),  'Sudan' ),
  (uuid_generate_v4(),  'Suriname' ),
  (uuid_generate_v4(),  'Svalbard and Jan Mayen' ),
  (uuid_generate_v4(),  'Swaziland' ),
  (uuid_generate_v4(),  'Sweden' ),
  (uuid_generate_v4(),  'Switzerland' ),
  (uuid_generate_v4(),  'Syria' ),
  (uuid_generate_v4(),  'Taiwan' ),
  (uuid_generate_v4(),  'Tajikistan' ),
  (uuid_generate_v4(),  'Tanzania' ),
  (uuid_generate_v4(),  'Thailand' ),
  (uuid_generate_v4(),  'East Timor' ),
  (uuid_generate_v4(),  'Togo' ),
  (uuid_generate_v4(),  'Tokelau' ),
  (uuid_generate_v4(),  'Tonga' ),
  (uuid_generate_v4(),  'Trinidad and Tobago' ),
  (uuid_generate_v4(),  'Tunisia' ),
  (uuid_generate_v4(),  'Turkey' ),
  (uuid_generate_v4(),  'Turkmenistan' ),
  (uuid_generate_v4(),  'Turks and Caicos Islands' ),
  (uuid_generate_v4(),  'Tuvalu' ),
  (uuid_generate_v4(),  'Uganda' ),
  (uuid_generate_v4(),  'Ukraine' ),
  (uuid_generate_v4(),  'United Arab Emirates' ),
  (uuid_generate_v4(),  'United Kingdom' ),
  (uuid_generate_v4(),  'United States' ),
  (uuid_generate_v4(),  'United States Outlying Islands' ),
  (uuid_generate_v4(),  'Uruguay' ),
  (uuid_generate_v4(),  'Uzbekistan' ),
  (uuid_generate_v4(),  'Vanuatu' ),
  (uuid_generate_v4(),  'Venezuela' ),
  (uuid_generate_v4(),  'Vietnam' ),
  (uuid_generate_v4(),  'British Virgin Islands' ),
  (uuid_generate_v4(),  'US Virgin Islands' ),
  (uuid_generate_v4(),  'Wallis and Futuna' ),
  (uuid_generate_v4(),  'Western Sahara' ),
  (uuid_generate_v4(),  'Yemen' ),
  (uuid_generate_v4(),  'Zambia' ),
  (uuid_generate_v4(),  'Zimbabwe' );

INSERT INTO region (id, name)
VALUES
  (uuid_generate_v4(), 'Oceania'),
  (uuid_generate_v4(), 'North America'),
  (uuid_generate_v4(), 'South America'),
  (uuid_generate_v4(), 'Africa'),
  (uuid_generate_v4(), 'Asia'),
  (uuid_generate_v4(), 'Europe');


